In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('players_data.csv')

In [8]:
df.head(10)

,commonName,firstName,lastName,country,club,position,composure,playStyle,playStyleId,height,...,sprintspeed,standingtackle,stamina,strength,vision,volleys,weakFoot,quality,isLoan,rating
0,Cristiano Ronaldo,C. Ronaldo,dos Santos Aveiro,Portugal,Juventus,ST,99,Basic,NaN,187,...,98,44,99,95,96,92,4,gold,NaN,99
1,NaN,Luka,Modrić,Croatia,Real Madrid,CM,91,Basic,NaN,172,...,85,99,99,77,99,94,4,gold,NaN,99
2,Cristiano Ronaldo,C. Ronaldo,dos Santos Aveiro,Portugal,Juventus,ST,99,Basic,NaN,187,...,99,44,99,93,95,92,4,gold,NaN,99
3,NaN,Lionel,Messi,Argentina,FC Barcelona,CF,99,Basic,NaN,170,...,94,39,99,82,99,93,4,gold,NaN,99
4,Cristiano Ronaldo,C. Ronaldo,dos Santos Aveiro,Portugal,Juventus,ST,99,Basic,NaN,187,...,99,44,99,93,95,92,4,gold,NaN,99
5,NaN,Lionel,Messi,Argentina,FC Barcelona,RW,99,Basic,NaN,170,...,91,33,84,69,99,93,4,gold,NaN,99
6,NaN,Lionel,Messi,Argentina,FC Barcelona,RW,99,Basic,NaN,170,...,96,37,92,75,99,93,4,gold,NaN,99
7,NaN,Lionel,Messi,Argentina,FC Barcelona,RW,99,Basic,NaN,170,...,96,37,92,75,99,93,4,gold,NaN,99
8,Pelé,Edson,Arantes Nascimento,Brazil,Icons,CAM,98,Basic,NaN,173,...,95,53,86,76,97,95,4,gold,NaN,98
9,Cristiano Ronaldo,C. Ronaldo,dos Santos Aveiro,Portugal,Juventus,ST,99,Basic,NaN,187,...,95,35,94,85,87,91,4,gold,NaN,98

In [6]:
df.shape

(21791, 53)

In [7]:
df.duplicated().sum()

1064

In [9]:
df['isLoan'].unique()

array([nan])